[project]
name = "dataanalyse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "duckdb>=1.2.1",
    "matplotlib>=3.10.1",
    "pyarrow>=19.0.1",
    "yfinance>=0.2.54",
]
